require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/impressions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Impression. As you add validations to Impression, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Impression.create! valid_attributes
      get impressions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      impression = Impression.create! valid_attributes
      get impression_url(impression)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_impression_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      impression = Impression.create! valid_attributes
      get edit_impression_url(impression)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Impression" do
        expect {
          post impressions_url, params: {impression: valid_attributes}
        }.to change(Impression, :count).by(1)
      end

      it "redirects to the created impression" do
        post impressions_url, params: {impression: valid_attributes}
        expect(response).to redirect_to(impression_url(Impression.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Impression" do
        expect {
          post impressions_url, params: {impression: invalid_attributes}
        }.not_to change(Impression, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post impressions_url, params: {impression: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested impression" do
        impression = Impression.create! valid_attributes
        patch impression_url(impression), params: {impression: new_attributes}
        impression.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the impression" do
        impression = Impression.create! valid_attributes
        patch impression_url(impression), params: {impression: new_attributes}
        impression.reload
        expect(response).to redirect_to(impression_url(impression))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        impression = Impression.create! valid_attributes
        patch impression_url(impression), params: {impression: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested impression" do
      impression = Impression.create! valid_attributes
      expect {
        delete impression_url(impression)
      }.to change(Impression, :count).by(-1)
    end

    it "redirects to the impressions list" do
      impression = Impression.create! valid_attributes
      delete impression_url(impression)
      expect(response).to redirect_to(impressions_url)
    end
  end
end
