require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/piazza_activity_breakdowns" do
  # This should return the minimal set of attributes required to create a valid
  # PiazzaActivityBreakdown. As you add validations to PiazzaActivityBreakdown, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PiazzaActivityBreakdown.create! valid_attributes
      get piazza_activity_breakdowns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
      get piazza_activity_breakdown_url(piazza_activity_breakdown)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_piazza_activity_breakdown_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
      get edit_piazza_activity_breakdown_url(piazza_activity_breakdown)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PiazzaActivityBreakdown" do
        expect {
          post piazza_activity_breakdowns_url, params: {piazza_activity_breakdown: valid_attributes}
        }.to change(PiazzaActivityBreakdown, :count).by(1)
      end

      it "redirects to the created piazza_activity_breakdown" do
        post piazza_activity_breakdowns_url, params: {piazza_activity_breakdown: valid_attributes}
        expect(response).to redirect_to(piazza_activity_breakdown_url(PiazzaActivityBreakdown.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PiazzaActivityBreakdown" do
        expect {
          post piazza_activity_breakdowns_url, params: {piazza_activity_breakdown: invalid_attributes}
        }.not_to change(PiazzaActivityBreakdown, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post piazza_activity_breakdowns_url, params: {piazza_activity_breakdown: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested piazza_activity_breakdown" do
        piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
        patch piazza_activity_breakdown_url(piazza_activity_breakdown), params: {piazza_activity_breakdown: new_attributes}
        piazza_activity_breakdown.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the piazza_activity_breakdown" do
        piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
        patch piazza_activity_breakdown_url(piazza_activity_breakdown), params: {piazza_activity_breakdown: new_attributes}
        piazza_activity_breakdown.reload
        expect(response).to redirect_to(piazza_activity_breakdown_url(piazza_activity_breakdown))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
        patch piazza_activity_breakdown_url(piazza_activity_breakdown), params: {piazza_activity_breakdown: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested piazza_activity_breakdown" do
      piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
      expect {
        delete piazza_activity_breakdown_url(piazza_activity_breakdown)
      }.to change(PiazzaActivityBreakdown, :count).by(-1)
    end

    it "redirects to the piazza_activity_breakdowns list" do
      piazza_activity_breakdown = PiazzaActivityBreakdown.create! valid_attributes
      delete piazza_activity_breakdown_url(piazza_activity_breakdown)
      expect(response).to redirect_to(piazza_activity_breakdowns_url)
    end
  end
end
