require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rfp_idea_submissions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RfpIdeaSubmission. As you add validations to RfpIdeaSubmission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RfpIdeaSubmission.create! valid_attributes
      get rfp_idea_submissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
      get rfp_idea_submission_url(rfp_idea_submission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rfp_idea_submission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
      get edit_rfp_idea_submission_url(rfp_idea_submission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RfpIdeaSubmission" do
        expect {
          post rfp_idea_submissions_url, params: {rfp_idea_submission: valid_attributes}
        }.to change(RfpIdeaSubmission, :count).by(1)
      end

      it "redirects to the created rfp_idea_submission" do
        post rfp_idea_submissions_url, params: {rfp_idea_submission: valid_attributes}
        expect(response).to redirect_to(rfp_idea_submission_url(RfpIdeaSubmission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RfpIdeaSubmission" do
        expect {
          post rfp_idea_submissions_url, params: {rfp_idea_submission: invalid_attributes}
        }.not_to change(RfpIdeaSubmission, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post rfp_idea_submissions_url, params: {rfp_idea_submission: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rfp_idea_submission" do
        rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
        patch rfp_idea_submission_url(rfp_idea_submission), params: {rfp_idea_submission: new_attributes}
        rfp_idea_submission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rfp_idea_submission" do
        rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
        patch rfp_idea_submission_url(rfp_idea_submission), params: {rfp_idea_submission: new_attributes}
        rfp_idea_submission.reload
        expect(response).to redirect_to(rfp_idea_submission_url(rfp_idea_submission))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
        patch rfp_idea_submission_url(rfp_idea_submission), params: {rfp_idea_submission: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rfp_idea_submission" do
      rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
      expect {
        delete rfp_idea_submission_url(rfp_idea_submission)
      }.to change(RfpIdeaSubmission, :count).by(-1)
    end

    it "redirects to the rfp_idea_submissions list" do
      rfp_idea_submission = RfpIdeaSubmission.create! valid_attributes
      delete rfp_idea_submission_url(rfp_idea_submission)
      expect(response).to redirect_to(rfp_idea_submissions_url)
    end
  end
end
